### ISSUE TITLE
Permission error 

### ISSUE THREAD

**Issue by sjmgarnier** [dm3ll3n/ShinyStudio#17]
When trying to install ShinyStudio, I get the following error message: 

```
Generating a RSA private key
....+++++
................+++++
writing new private key to '/etc/letsencrypt/live/example.com/privkey.pem'
-----
Building shinystudio
Traceback (most recent call last):
  File "site-packages/docker/utils/build.py", line 96, in create_archive
PermissionError: [Errno 13] Permission denied: '/home/simon/ShinyStudio/config/container/letsencrypt/live/example.com/privkey.pem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1077, in up
  File "compose/cli/main.py", line 1073, in up
  File "compose/project.py", line 548, in up
  File "compose/service.py", line 367, in ensure_image_exists
  File "compose/service.py", line 1106, in build
  File "site-packages/docker/api/build.py", line 160, in build
  File "site-packages/docker/utils/build.py", line 31, in tar
  File "site-packages/docker/utils/build.py", line 100, in create_archive
OSError: Can not read file in context: /home/simon/ShinyStudio/config/container/letsencrypt/live/example.com/privkey.pem
[31996] Failed to execute script docker-compose
ERROR: No container found for nginx_1
```
Any idea what's wrong here?

**Comment by sjmgarnier** [comment]
For some reason `ShinyStudio/config/container/letsencrypt/` is owned by root
